namespace: oo
name: orchestration
version: 1.0.0
readme: README.md
authors:
- Daniel Crisan <danielcrisan@ymail.com>
description: Ansible collection for interacting with Operations Orchestration
license_file: ''
tags:
  - orchestration
  - oo
  - opentext
repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore



